<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\UpsMonitor.Core\UpsMonitor.Core.csproj" />
    <ProjectReference Include="..\UpsMonitor.Hid\UpsMonitor.Hid.csproj" />
    <ProjectReference Include="..\UpsMonitor.Infrastructure\UpsMonitor.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ApplicationIcon>Resources\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\app.png" />
    <Resource Include="Resources\app.ico" />
  </ItemGroup>

</Project>
